//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIF.Visualization.Excel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIF.Visualization.Excel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug file error.
        /// </summary>
        public static string DebugReadWriteError_MessageBoxTitle {
            get {
                return ResourceManager.GetString("DebugReadWriteError_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create or delete the debug file, check that you have write permissions for .
        /// </summary>
        public static string DebugReadWriteErrorPre_MessageBoxText {
            get {
                return ResourceManager.GetString("DebugReadWriteErrorPre_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , or create it yourself..
        /// </summary>
        public static string DebugReadWriteErrorSuf_MessageBoxText {
            get {
                return ResourceManager.GetString("DebugReadWriteErrorSuf_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , or create it yourself..
        /// </summary>
        public static string DebugReadWriteErrorSuff_MessageBoxText {
            get {
                return ResourceManager.GetString("DebugReadWriteErrorSuff_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIF or JRE not installed.
        /// </summary>
        public static string GlobalSettingsDialog_B_VerifySifPath_Click_SIF_or_JRE_not_installed {
            get {
                return ResourceManager.GetString("GlobalSettingsDialog_B_VerifySifPath_Click_SIF_or_JRE_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap input_clear {
            get {
                object obj = ResourceManager.GetObject("input_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap inspectionpane {
            get {
                object obj = ResourceManager.GetObject("inspectionpane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap intermediate_clear {
            get {
                object obj = ResourceManager.GetObject("intermediate_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install the Java version of SIF to the specified directory or choose a new one and install the Java Runtime Environment and add it to your PATH system variable.
        /// </summary>
        public static string NoJreSifInstallationError_MessageBoxText {
            get {
                return ResourceManager.GetString("NoJreSifInstallationError_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIF or JRE not installed.
        /// </summary>
        public static string NoJreSifInstallationError_MessageBoxTitle {
            get {
                return ResourceManager.GetString("NoJreSifInstallationError_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install the .NET version of SIF to the specified directory or choose a new one, install the Mono Runtime Environment and add it to your PATH system variable or enter via &quot;Browse...&quot; if you don&apos;t want to use the .NET framework and install the IKVM assemblies to the Assembly Cache.
        /// </summary>
        public static string NoMonoSifInstallaionError_MessageBoxText {
            get {
                return ResourceManager.GetString("NoMonoSifInstallaionError_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIF or Mono Runtime Environment not installed.
        /// </summary>
        public static string NoMonoSifInstallationError_MessageBoxTitle {
            get {
                return ResourceManager.GetString("NoMonoSifInstallationError_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap output_clear {
            get {
                object obj = ResourceManager.GetObject("output_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string tl_Archive {
            get {
                return ResourceManager.GetString("tl_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell definitions.
        /// </summary>
        public static string tl_CellDefinitions {
            get {
                return ResourceManager.GetString("tl_CellDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string tl_CellErrorInfo_Background {
            get {
                return ResourceManager.GetString("tl_CellErrorInfo_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Solution.
        /// </summary>
        public static string tl_CellErrorInfo_PossibleSolution {
            get {
                return ResourceManager.GetString("tl_CellErrorInfo_PossibleSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        public static string tl_Ignored {
            get {
                return ResourceManager.GetString("tl_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ignored violations. Please ignore violations if this is necessary..
        /// </summary>
        public static string tl_IgnoreView_Empty {
            get {
                return ResourceManager.GetString("tl_IgnoreView_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to violation(s) in list.
        /// </summary>
        public static string tl_IgnoreView_InList {
            get {
                return ResourceManager.GetString("tl_IgnoreView_InList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string tl_Later {
            get {
                return ResourceManager.GetString("tl_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No findings for later.
        /// </summary>
        public static string tl_LaterView_Empty {
            get {
                return ResourceManager.GetString("tl_LaterView_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following parts were unable to load:.
        /// </summary>
        public static string tl_Load_Failed {
            get {
                return ResourceManager.GetString("tl_Load_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading from workbook failed.
        /// </summary>
        public static string tl_Load_Failed_Title {
            get {
                return ResourceManager.GetString("tl_Load_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inspection queue has been cleared due to memory restrictions..
        /// </summary>
        public static string tl_MemoryRestrictions {
            get {
                return ResourceManager.GetString("tl_MemoryRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string tl_MessageBox_Error {
            get {
                return ResourceManager.GetString("tl_MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string tl_MessageBox_No {
            get {
                return ResourceManager.GetString("tl_MessageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string tl_MessageBox_Ok {
            get {
                return ResourceManager.GetString("tl_MessageBox_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled new scenario.
        /// </summary>
        public static string tl_NewScenarioDialog_DefaultAnswer {
            get {
                return ResourceManager.GetString("tl_NewScenarioDialog_DefaultAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give your scenario a name:.
        /// </summary>
        public static string tl_NewScenarioDialog_Question {
            get {
                return ResourceManager.GetString("tl_NewScenarioDialog_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scenario....
        /// </summary>
        public static string tl_NewScenarioDialog_Title {
            get {
                return ResourceManager.GetString("tl_NewScenarioDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No java runtime was found!
        ///Please ensure a Java runtime environment &gt;= 1.7 is installed and accessible through the PATH variable.
        ///The Scan button will be without function..
        /// </summary>
        public static string tl_No_Java_Enviroment {
            get {
                return ResourceManager.GetString("tl_No_Java_Enviroment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaning not avaliable right now.
        /// </summary>
        public static string tl_NoScanPossible {
            get {
                return ResourceManager.GetString("tl_NoScanPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scenarios created. Please create a new scenario from the Ribbon menu..
        /// </summary>
        public static string tl_NoScenariosSide {
            get {
                return ResourceManager.GetString("tl_NoScenariosSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number format.
        /// </summary>
        public static string tl_Number_Format {
            get {
                return ResourceManager.GetString("tl_Number_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string tl_Open {
            get {
                return ResourceManager.GetString("tl_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No open findings.
        /// </summary>
        public static string tl_OpenView_Empty {
            get {
                return ResourceManager.GetString("tl_OpenView_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough memory (RAM) to scan the file.
        /// </summary>
        public static string tl_OutOfMemory {
            get {
                return ResourceManager.GetString("tl_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install the Spreadsheet Inspection Framework and restart Excel..
        /// </summary>
        public static string tl_Path_install {
            get {
                return ResourceManager.GetString("tl_Path_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Spreadsheet Inspection Framework was not found at this location:
        ///.
        /// </summary>
        public static string tl_Path_missing {
            get {
                return ResourceManager.GetString("tl_Path_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string tl_PolicyConfiguration_Button_Cancel {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string tl_PolicyConfiguration_Button_Ok {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string tl_PolicyConfiguration_Label_Always {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Label_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string tl_PolicyConfiguration_Label_Manual {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Label_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask whether thousand separators are intended.
        /// </summary>
        public static string tl_PolicyConfiguration_Label_ThousandSeparators {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Label_ThousandSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constants in formulas.
        /// </summary>
        public static string tl_PolicyConfiguration_No_Constants {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_No_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells with #Errors.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_CellsWithErrors {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_CellsWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants in Formulas.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_Constants {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Complexity.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_FormulaComplexity {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_FormulaComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-considered constants.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_NonConsideredConstants {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_NonConsideredConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One among others.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_OneAmongOthers {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_OneAmongOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading direction.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_ReadingDirection {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_ReadingDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References to blank cells.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_ReferencesToBlankCells {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_ReferencesToBlankCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same reference multiple times.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_SameMultipleRefs {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_SameMultipleRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String distance.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_StringDistance {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_StringDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum distance:.
        /// </summary>
        public static string tl_PolicyConfiguration_Rule_StringDistanceExtra {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_Rule_StringDistanceExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Configuration.
        /// </summary>
        public static string tl_PolicyConfiguration_WindowTitle {
            get {
                return ResourceManager.GetString("tl_PolicyConfiguration_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing scan.
        /// </summary>
        public static string tl_ProcessingScan {
            get {
                return ResourceManager.GetString("tl_ProcessingScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Cell.
        /// </summary>
        public static string tl_Ribbon_AreaDefine_Inputcell {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaDefine_Inputcell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines a Input Cell..
        /// </summary>
        public static string tl_Ribbon_AreaDefine_InputcellTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaDefine_InputcellTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Cell.
        /// </summary>
        public static string tl_Ribbon_AreaDefine_Intermediatecell {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaDefine_Intermediatecell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines a Intermediate Cell..
        /// </summary>
        public static string tl_Ribbon_AreaDefine_IntermediatecellTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaDefine_IntermediatecellTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Cell.
        /// </summary>
        public static string tl_Ribbon_AreaDefine_Resultcell {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaDefine_Resultcell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines a Result Cell..
        /// </summary>
        public static string tl_Ribbon_AreaDefine_ResultcellTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaDefine_ResultcellTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Scenario Cells.
        /// </summary>
        public static string tl_Ribbon_AreaDefine_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaDefine_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string tl_Ribbon_AreaMiscellaneous_GlobalSettingsButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaMiscellaneous_GlobalSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sanity controls.
        /// </summary>
        public static string tl_Ribbon_AreaMiscellaneous_ShowSanity {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaMiscellaneous_ShowSanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string tl_Ribbon_AreaMiscellaneous_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaMiscellaneous_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic scans.
        /// </summary>
        public static string tl_Ribbon_AreaScan_AutomaticScansCheckbox {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_AutomaticScansCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tl_Ribbon_AreaScan_AutomaticScansCheckboxTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_AutomaticScansCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy configuration.
        /// </summary>
        public static string tl_Ribbon_AreaScan_PolicyConfigurationButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_PolicyConfigurationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tl_Ribbon_AreaScan_PolicyConfigurationButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_PolicyConfigurationButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string tl_Ribbon_AreaScan_ScanButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_ScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans the current workbook with all scenarios..
        /// </summary>
        public static string tl_Ribbon_AreaScan_ScanButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_ScanButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string tl_Ribbon_AreaScan_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_CancelButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard this scenario.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_CancelButtonTolltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_CancelButtonTolltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_NewButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new scenario.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_NewButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_NewButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_SaveButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this scenario.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_SaveButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Pane.
        /// </summary>
        public static string tl_Ribbon_AreaView_PaneButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_PaneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a pane with the cell definitions, scenario overview and findings..
        /// </summary>
        public static string tl_Ribbon_AreaView_PaneButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_PaneButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset document.
        /// </summary>
        public static string tl_Ribbon_AreaView_ResetButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the document to the state before the test execution..
        /// </summary>
        public static string tl_Ribbon_AreaView_ResetButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_ResetButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string tl_Ribbon_AreaView_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No policies are enabled for manual scans. Please enable at least one policy and try again..
        /// </summary>
        public static string tl_Ribbon_MessageNoPolicies {
            get {
                return ResourceManager.GetString("tl_Ribbon_MessageNoPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string tl_Ribbon_MessageNoPolicies_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_MessageNoPolicies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot run a scan while editing a scenario. Save or discard the scenario and try again..
        /// </summary>
        public static string tl_Ribbon_MessageNoScansInScnearioMode {
            get {
                return ResourceManager.GetString("tl_Ribbon_MessageNoScansInScnearioMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning not possible now.
        /// </summary>
        public static string tl_Ribbon_MessageNoScansInScnearioModeTitle {
            get {
                return ResourceManager.GetString("tl_Ribbon_MessageNoScansInScnearioModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSPECTION.
        /// </summary>
        public static string tl_Ribbon_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test of the current document failed!
        ///.
        /// </summary>
        public static string tl_Scan_failed {
            get {
                return ResourceManager.GetString("tl_Scan_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan aborted.
        /// </summary>
        public static string tl_Scan_needingsavetitle {
            get {
                return ResourceManager.GetString("tl_Scan_needingsavetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file needs to be saved before a scan can be done. 
        ///Scan will be aborted .
        /// </summary>
        public static string tl_Scan_needssave {
            get {
                return ResourceManager.GetString("tl_Scan_needssave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan successful.
        /// </summary>
        public static string tl_Scan_successful {
            get {
                return ResourceManager.GetString("tl_Scan_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan unsuccessful.
        /// </summary>
        public static string tl_Scan_unsuccessful {
            get {
                return ResourceManager.GetString("tl_Scan_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan failed.
        ///.
        /// </summary>
        public static string tl_Scan_unsuccessfulMessage {
            get {
                return ResourceManager.GetString("tl_Scan_unsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can\&apos;t create scenario.
        /// </summary>
        public static string tl_Scenario_CantCreate {
            get {
                return ResourceManager.GetString("tl_Scenario_CantCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scenario needs at least one input cell value..
        /// </summary>
        public static string tl_Scenario_MinOneInput {
            get {
                return ResourceManager.GetString("tl_Scenario_MinOneInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scenario needs at least one output cell value..
        /// </summary>
        public static string tl_Scenario_MinOneOutput {
            get {
                return ResourceManager.GetString("tl_Scenario_MinOneOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t fill all selected input-, output- and itermediatecells.
        ///Possible solutions:
        ///- fill these missing cells
        ///- abort the scenario creation.
        ///- delete unncessaryselected cells and try it again..
        /// </summary>
        public static string tl_Scenario_Notallcellsfilled {
            get {
                return ResourceManager.GetString("tl_Scenario_Notallcellsfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete cell.
        /// </summary>
        public static string tl_ScenarioDetailPane_DeleteData {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected cell.
        /// </summary>
        public static string tl_ScenarioDetailPane_DeleteDataTooltip {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_DeleteDataTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string tl_ScenarioDetailPane_DiscardData {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_DiscardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard the changes?.
        /// </summary>
        public static string tl_ScenarioDetailPane_DiscardDataMessageBox {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_DiscardDataMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string tl_ScenarioDetailPane_DiscardDataMessageBoxTitle {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_DiscardDataMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discards the changes on the selected scenario.
        /// </summary>
        public static string tl_ScenarioDetailPane_DiscardDataTooltip {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_DiscardDataTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string tl_ScenarioDetailPane_SaveData {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes in the open scenario.
        /// </summary>
        public static string tl_ScenarioDetailPane_SaveDataTooltip {
            get {
                return ResourceManager.GetString("tl_ScenarioDetailPane_SaveDataTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Overview.
        /// </summary>
        public static string tl_ScenarioOverview {
            get {
                return ResourceManager.GetString("tl_ScenarioOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the scenario named.
        /// </summary>
        public static string tl_ScenarioPane_DeleteConfirmQuestion {
            get {
                return ResourceManager.GetString("tl_ScenarioPane_DeleteConfirmQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete scenario.
        /// </summary>
        public static string tl_ScenarioPane_DeleteConfirmQuestionTitle {
            get {
                return ResourceManager.GetString("tl_ScenarioPane_DeleteConfirmQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete scenario.
        /// </summary>
        public static string tl_ScenarioPane_DeleteScenario {
            get {
                return ResourceManager.GetString("tl_ScenarioPane_DeleteScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected scenario.
        /// </summary>
        public static string tl_ScenarioPane_DeleteScenarioTooltip {
            get {
                return ResourceManager.GetString("tl_ScenarioPane_DeleteScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string tl_ScenarioPane_EditScenario {
            get {
                return ResourceManager.GetString("tl_ScenarioPane_EditScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a new window to edit the scenario.
        /// </summary>
        public static string tl_ScenarioPane_EditScenarioTooltip {
            get {
                return ResourceManager.GetString("tl_ScenarioPane_EditScenarioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scenarios created. Please create a new scenario from the Ribbon menu..
        /// </summary>
        public static string tl_ScenarioPane_NoScenarios {
            get {
                return ResourceManager.GetString("tl_ScenarioPane_NoScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes don\&apos;t show again.
        /// </summary>
        public static string tl_Separator_Confirmed_all {
            get {
                return ResourceManager.GetString("tl_Separator_Confirmed_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, ignore it in this field.
        /// </summary>
        public static string tl_Separator_Confirmed_this {
            get {
                return ResourceManager.GetString("tl_Separator_Confirmed_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have used a thousands separator character, was this intended behavior?.
        /// </summary>
        public static string tl_Separator_intended {
            get {
                return ResourceManager.GetString("tl_Separator_intended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived findings.
        /// </summary>
        public static string tl_SharedPane_Archived {
            get {
                return ResourceManager.GetString("tl_SharedPane_Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked cells.
        /// </summary>
        public static string tl_SharedPane_Cells {
            get {
                return ResourceManager.GetString("tl_SharedPane_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored findings.
        /// </summary>
        public static string tl_SharedPane_Ignored {
            get {
                return ResourceManager.GetString("tl_SharedPane_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Findings for later.
        /// </summary>
        public static string tl_SharedPane_Later {
            get {
                return ResourceManager.GetString("tl_SharedPane_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open findings.
        /// </summary>
        public static string tl_SharedPane_Open {
            get {
                return ResourceManager.GetString("tl_SharedPane_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string tl_SharedPane_Scenarios {
            get {
                return ResourceManager.GetString("tl_SharedPane_Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunatly SIFCore crashed.
        ///Try scanning the file again and if this doesn&apos;t help close and open the file again..
        /// </summary>
        public static string tl_SIFCorecrashed {
            get {
                return ResourceManager.GetString("tl_SIFCorecrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solved findings.
        /// </summary>
        public static string tl_SolvedView_Empty {
            get {
                return ResourceManager.GetString("tl_SolvedView_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start a new Scans.
        /// </summary>
        public static string tl_StartNewScan {
            get {
                return ResourceManager.GetString("tl_StartNewScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop editing the cell and start a new scan.
        /// </summary>
        public static string tl_stopEdit {
            get {
                return ResourceManager.GetString("tl_stopEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation caused an error!
        ///.
        /// </summary>
        public static string tl_ValidationError {
            get {
                return ResourceManager.GetString("tl_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        public static string tl_ViolationTemplate_Background {
            get {
                return ResourceManager.GetString("tl_ViolationTemplate_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string tl_ViolationTemplate_Description {
            get {
                return ResourceManager.GetString("tl_ViolationTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First occurence:.
        /// </summary>
        public static string tl_ViolationTemplate_FirstOccurence {
            get {
                return ResourceManager.GetString("tl_ViolationTemplate_FirstOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less details.
        /// </summary>
        public static string tl_ViolationTemplate_LessDetails {
            get {
                return ResourceManager.GetString("tl_ViolationTemplate_LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string tl_ViolationTemplate_MoreDetails {
            get {
                return ResourceManager.GetString("tl_ViolationTemplate_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible solution:.
        /// </summary>
        public static string tl_ViolationTemplate_PossibleSolution {
            get {
                return ResourceManager.GetString("tl_ViolationTemplate_PossibleSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string tl_ViolationTemplate_Type {
            get {
                return ResourceManager.GetString("tl_ViolationTemplate_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to violation(s) in list.
        /// </summary>
        public static string tl_ViolationView_Footer {
            get {
                return ResourceManager.GetString("tl_ViolationView_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignore.
        /// </summary>
        public static string tl_ViolationView_Ignore {
            get {
                return ResourceManager.GetString("tl_ViolationView_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string tl_ViolationView_Later {
            get {
                return ResourceManager.GetString("tl_ViolationView_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vdynamic {
            get {
                object obj = ResourceManager.GetObject("Vdynamic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vsanity {
            get {
                object obj = ResourceManager.GetObject("Vsanity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vstatic {
            get {
                object obj = ResourceManager.GetObject("Vstatic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
