//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIF.Visualization.Excel.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIF.Visualization.Excel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap input_clear {
            get {
                object obj = ResourceManager.GetObject("input_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap inspectionpane {
            get {
                object obj = ResourceManager.GetObject("inspectionpane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap intermediate_clear {
            get {
                object obj = ResourceManager.GetObject("intermediate_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap output_clear {
            get {
                object obj = ResourceManager.GetObject("output_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ignored violations. Please ignore violations if this is necessary. ähnelt.
        /// </summary>
        public static string tl_IgnoreView_Empty {
            get {
                return ResourceManager.GetString("tl_IgnoreView_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die violation(s) in list ähnelt.
        /// </summary>
        public static string tl_IgnoreView_InList {
            get {
                return ResourceManager.GetString("tl_IgnoreView_InList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic scans ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScan_AutomaticScansCheckbox {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_AutomaticScansCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScan_AutomaticScansCheckboxTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_AutomaticScansCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Policy configuration ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScan_PolicyConfigurationButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_PolicyConfigurationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScan_PolicyConfigurationButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_PolicyConfigurationButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScan_ScanButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_ScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scans the current workbook with all scenarios. ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScan_ScanButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_ScanButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScan_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_CancelButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discard this scenario ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_CancelButtonTolltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_CancelButtonTolltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_NewButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new scenario ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_NewButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_NewButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_SaveButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save this scenario ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_SaveButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scenario ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaScenario_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaScenario_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inspection Pane ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaView_PaneButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_PaneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opens a pane with the cell definitions, scenario overview and findings. ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaView_PaneButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_PaneButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset document ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaView_ResetButton {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resets the document to the state before the test execution. ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaView_ResetButtonTooltip {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_ResetButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string tl_Ribbon_AreaView_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_AreaView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INSPECTION ähnelt.
        /// </summary>
        public static string tl_Ribbon_Title {
            get {
                return ResourceManager.GetString("tl_Ribbon_Title", resourceCulture);
            }
        }
    }
}
